In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('data_07.txt', unpack=True)
x_data = xy[0:-1]
y_data = xy[-1]

In [3]:
xy

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  0.]])

### xor을 logistic regression을 해서 풀 수있나?

In [9]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w = tf.Variable(tf.random_uniform([1,2], -1.0, 1.0))
b = tf.Variable(tf.zeros(1))

# hypothesis
h = tf.matmul(w,x)+b
hypothesis = 1/(1+tf.exp(-h))

cost = -tf.reduce_mean(y*tf.log(hypothesis) + (1-y)*tf.log(1-hypothesis))

a = tf.constant(0.01)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.initialize_all_variables())

for i in range(1001):
    sess.run(train, feed_dict = {x:x_data, y:y_data})
    
    # fit the line
    if(i%200 ==0):
        print(i, sess.run(cost, feed_dict = {x:x_data, y:y_data}), sess.run(w))
        
    if(i != 0 and i%200 ==0):
        # test model
        correct_prediction = tf.equal(tf.floor(hypothesis+0.5), y)
        #calculate accuracy
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))
        print(sess.run([hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], feed_dict = {x:x_data, y:y_data}))

0 0.707638 [[ 0.02515462 -0.49649304]]
200 0.699428 [[ 0.05812536 -0.40286264]]
[array([[ 0.51936644,  0.41937047,  0.53385556,  0.43358657]], dtype=float32), array([[ 1.,  0.,  1.,  0.]], dtype=float32), array([[False, False,  True,  True]], dtype=bool), 0.5]
400 0.697055 [[ 0.06500284 -0.34204844]]
[array([[ 0.52668381,  0.44146666,  0.54285449,  0.4575502 ]], dtype=float32), array([[ 1.,  0.,  1.,  0.]], dtype=float32), array([[False, False,  True,  True]], dtype=bool), 0.5]
600 0.696043 [[ 0.06106298 -0.29828486]]
[array([[ 0.52865517,  0.45424378,  0.54383951,  0.46941933]], dtype=float32), array([[ 1.,  0.,  1.,  0.]], dtype=float32), array([[False, False,  True,  True]], dtype=bool), 0.5]
800 0.695419 [[ 0.05321947 -0.26398593]]
[array([[ 0.52829933,  0.46240422,  0.54153848,  0.47565722]], dtype=float32), array([[ 1.,  0.,  1.,  0.]], dtype=float32), array([[False, False,  True,  True]], dtype=bool), 0.5]
1000 0.69496 [[ 0.04449194 -0.23549588]]
[array([[ 0.52698255,  0.4681779

### 그렇다면 neural network?

In [3]:
x_data_t = x_data.transpose()
y_data_t = y_data.transpose()
y_data_t =  [[0],[1],[1],[0]]
y_data_t

[[0], [1], [1], [0]]

In [4]:
with tf.name_scope('input') as scope:
    x_ = tf.placeholder(tf.float32, shape=[4,2], name="x-input")
    y_ = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

with tf.name_scope('weight') as scope:
    w1 = tf.Variable(tf.random_uniform([2,2], -1.0, 1.0), name='w1')
    w2 = tf.Variable(tf.random_uniform([2,1], -1.0, 1.0), name='w2')
    
with tf.name_scope('bias') as scope:
    b1 = tf.Variable(tf.zeros([2]), name='bias1')
    b2 = tf.Variable(tf.zeros([1]), name='bias2')


# hypothesis
with tf.name_scope('layer1') as scope:
    l2 = tf.sigmoid(tf.matmul(x_,w1)+b1)
with tf.name_scope('last') as scope:
    hypothesis = tf.sigmoid(tf.matmul(l2,w2)+b2)

# cost
with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(y_*tf.log(hypothesis) + (1-y_)*tf.log(1-hypothesis))

    
# summary
tf.summary.scalar('cost', cost)
    
    
# train
with tf.name_scope('train') as scope:
    train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cost)


# merge
merged = tf.merge_all_summaries()
writer =tf.train.SummaryWriter("./log/nntest", sess.graph)

sess =  tf.Session()
init = tf.initialize_all_variables()
sess.run(init)

for i in range(10001):
    sess.run(train_step, feed_dict = {x_:x_data_t, y_:y_data_t})
    
    # fit the line
    if(i%500 ==0):
        print(i, sess.run(cost, feed_dict = {x_:x_data_t, y_:y_data_t}))
        summary = sess.run(merged, feed_dict = {x_:x_data_t, y_:y_data_t})
        writer.add_summary(summary,i)

        

NameError: name 'sess' is not defined

In [31]:
x_data.transpose()

array([[ 0.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  1.]])

In [32]:
x_data

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.]])