In [19]:
import tensorflow as tf
import numpy as np

In [21]:
xy

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  1.,  1.,  0.]])

In [22]:
x_data = xy[0:-1]
y_data = xy[-1]

In [23]:
x_data

array([[ 0.,  0.,  1.,  1.],
       [ 0.,  1.,  0.,  1.]])

In [24]:
x_data_t = x_data.transpose()
y_data_t = y_data.transpose()

In [25]:
y_data_t = [[0],[1],[1],[0]]

In [27]:
print(x_data_t)
print('')
print(y_data_t)

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]

[[0], [1], [1], [0]]


In [1]:
x = tf.placeholder(tf.float32, shape=[4,2], name='x-input')
y = tf.placeholder(tf.float32, shape=[4,1], name='y-input')


# variable
w1 = tf.Variable(tf.random_uniform([2,5], -1.0, 1.0), name='weight1')
w2 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight2')
w3 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight3')
w4 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight4')
w5 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight5')
w6 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight6')
w7 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight7')
w8 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight8')
w9 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight9')
w10 = tf.Variable(tf.random_uniform([5,5], -1.0, 1.0), name='weight10')
w11 = tf.Variable(tf.random_uniform([5,1], -1.0, 1.0), name='weight11')

b1 = tf.Variable(tf.zeros([5]), name='bias1')
b2 = tf.Variable(tf.zeros([5]), name='bias2')
b3 = tf.Variable(tf.zeros([5]), name='bias3')
b4 = tf.Variable(tf.zeros([5]), name='bias4')
b5 = tf.Variable(tf.zeros([5]), name='bias5')
b6 = tf.Variable(tf.zeros([5]), name='bias6')
b7 = tf.Variable(tf.zeros([5]), name='bias7')
b8 = tf.Variable(tf.zeros([5]), name='bias8')
b9 = tf.Variable(tf.zeros([5]), name='bias9')
b10 = tf.Variable(tf.zeros([5]), name='bias10')
b11 = tf.Variable(tf.zeros([1]), name='bias11')


# hypothesis
with tf.name_scope('layer1') as scope:
    l1 = tf.nn.relu(tf.matmul(x,w1)+b1)
with tf.name_scope('layer2') as scope:
    l2 = tf.nn.relu(tf.matmul(l1,w2)+b2)
with tf.name_scope('layer3') as scope:
    l3 = tf.nn.relu(tf.matmul(l2,w3)+b3)
with tf.name_scope('layer4') as scope:
    l4 = tf.nn.relu(tf.matmul(l3,w4)+b4)
with tf.name_scope('layer5') as scope:
    l5 = tf.nn.relu(tf.matmul(l4,w5)+b5)
with tf.name_scope('layer6') as scope:
    l6 = tf.nn.relu(tf.matmul(l5,w6)+b6)
with tf.name_scope('layer7') as scope:
    l7 = tf.nn.relu(tf.matmul(l6,w7)+b7)
with tf.name_scope('layer8') as scope:
    l8 = tf.nn.relu(tf.matmul(l7,w8)+b8)
with tf.name_scope('layer9') as scope:
    l9 = tf.nn.relu(tf.matmul(l8,w9)+b9)
with tf.name_scope('layer10') as scope:
    l10 = tf.nn.relu(tf.matmul(l9,w10)+b10)
    
with tf.name_scope('last') as scope:
    hypothesis = tf.sigmoid(tf.matmul(l10,w11)+b11)


# cost
with tf.name_scope('cost') as scope:
    cost = -tf.reduce_mean(y*tf.log(hypothesis) + (1-y)*tf.log(1-hypothesis))
    cost_summ = tf.scalar_summary('cost', cost)
    
# minimize
a = tf.constant(0.1)
with tf.name_scope('train') as scope:
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)
    

    
# tensorboard --logdir=./logs/xor_relu_logs

with tf.Session() as sess:
    merged = tf.merge_all_summaries()
    writer = tf.train.SummaryWriter('./logs/xor_relu_logs', sess.graph)

# init
sess.run(tf.initialize_all_variables())

for step in range(10001):
    sess.run(train, feed_dict ={x:x_data_t, y:y_data_t})
    # fit the line
    if(step%500 ==0):
        print(step, sess.run(cost, feed_dict ={x:x_data_t, y:y_data_t}))
#         summary = sess.run(merged, feed_dict ={x:x_data_t, y:y_data_t})
#         writer.add_summary(summary, step)
        

NameError: name 'tf' is not defined