### Character-level language modal example

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
char_rdic = ['h', 'e', 'l', 'o']
char_dic = {w: i for i,w in enumerate(char_rdic)}
ground_truth = [char_dic[c] for c in 'hello']

In [3]:
x_data = np.array([[1,0,0,0], # h
                 [0,1,0,0],   # e
                 [0,0,1,0],   # l
                 [0,0,1,0]],  # l
                 dtype='f')

In [8]:
x_data = tf.one_hot(ground_truth[:-1], len(char_dic), 1.0, 0.0, -1)
print(x_data)

Tensor("one_hot:0", shape=(4, 4), dtype=float32)


In [4]:
# configure
rnn_size = len(char_dic) # 4 => 출력의 개수
batch_size = 1
output_size = 4
time_step_size = len(char_dic)

In [5]:
# rnn model
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=rnn_size)
initial_state = rnn_cell.zero_state(batch_size, tf.float32)
x_split = tf.split(0, time_step_size, x_data)
outputs, state = tf.nn.rnn(cell=rnn_cell, inputs=x_split, initial_state=initial_state)

In [8]:
# cost => sequence_loss_by_example 사용 => 범용이기 때문에 원하는 포멧이 있음
# logits: list of 2D tensors of shape[batch_size*num_decoder_symbols]
# targets: list of 1D batch-sized int32 tensors of the same length as logits
# weights: list of 1D batch-sized float tensors of the same length as logits
logits = tf.reshape(tf.concat(1,outputs), [-1,rnn_size])
targets = tf.reshape(ground_truth[1:], [-1])
weights = tf.ones([time_step_size*batch_size])

loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss)/batch_size
train_op = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)

In [9]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(100):
        sess.run(train_op)
        result = sess.run(tf.arg_max(logits,1))
        print(result, [char_rdic[t] for t in result])

[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 0 1] ['o', 'o', 'h', 'e']
[3 3 2 1] ['o', 'o', 'l', 'e']
[3 3 2 1] ['o', 'o', 'l', 'e']
[3 3 2 1] ['o', 'o', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1] ['o', 'l', 'l', 'e']
[3 2 2 1

 #### Deep RNN


In [ ]:
one_cell = tf.nn.rnn_cell.BasicRNNCell(rnn_size)
rnn_cell = tf.nn.rnn_cell.MultiRNNCell([one_cell]*depth)